{
 "title": "Speedtester",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "label": "hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "mac", "label": "mac", "query": { "query": "label_values(mac)" } },
   { "name": "interface", "label": "interface", "query": { "query": "label_values(interface)" } },
   { "name": "internal_ip", "label": "internal_ip", "query": { "query": "label_values(internal_ip)" } },
   { "name": "server_ip", "label": "server_ip", "query": { "query": "label_values(server_ip)" } },
   { "name": "external_ip", "label": "external_ip", "query": { "query": "label_values(external_ip)" } },
   { "name": "providername", "label": "providername", "query": { "query": "label_values(providername)" } },
   { "name": "server", "label": "server", "query": { "query": "label_values(server)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "download_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upload_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw upload and download",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "download_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "upload_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "downlatency{hostname=\"$hostname\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "uplatency{hostname=\"$hostname\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pinglatency{hostname=\"$hostname\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "packetloss{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "upload_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "download_Mbps{hostname=\"$hostname\", job=\"$job\", mac=\"$mac\", interface=\"$interface\", internal_ip=\"$internal_ip\", server_ip=\"$server_ip\", providername=\"$providername\", server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}